#!/usr/bin/env python3

import argparse
import sugar.lib.exceptions
from sugarsdk.gendoc import ModuleDocumentationGenerator


__version__ = "0.0.1 Alpha"


def main():
    """
    Main function.

    :return:
    """
    parser = argparse.ArgumentParser(description="Sugar Module Documentation Generator, {}".format(__version__))
    parser.add_argument("-o", "--out", help="Output directory.")
    parser.add_argument("-f", "--force", help="Overwrite existing documentation files, if any.", action="store_true")
    args = parser.parse_args()

    try:
        ModuleDocumentationGenerator(args).generate()
    except sugar.lib.exceptions.SugarException as exc:
        parser.print_usage()
        print("\n{}\n".format(exc))


if __name__ == "__main__":
    main()
